// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHZL-m2A3mdfyvj97sysMz8571qGdmCmQ',
    appId: '1:957380617692:web:08ca4b20a10771299a1b19',
    messagingSenderId: '957380617692',
    projectId: 'notiva-61aff',
    authDomain: 'notiva-61aff.firebaseapp.com',
    storageBucket: 'notiva-61aff.firebasestorage.app',
    measurementId: 'G-V5DPMXWMVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBicN0CzAclrr5Z7FMOccILQYMhuc8V1I8',
    appId: '1:957380617692:android:083e7ca32730a8a69a1b19',
    messagingSenderId: '957380617692',
    projectId: 'notiva-61aff',
    storageBucket: 'notiva-61aff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfuPzqmG58qE4YMhof718OWdZCFALsNOA',
    appId: '1:957380617692:ios:186fb139644c3ed79a1b19',
    messagingSenderId: '957380617692',
    projectId: 'notiva-61aff',
    storageBucket: 'notiva-61aff.firebasestorage.app',
    iosClientId: '957380617692-imk3edfaa2ccbi0iuoi0avg165d871jh.apps.googleusercontent.com',
    iosBundleId: 'com.example.notivaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfuPzqmG58qE4YMhof718OWdZCFALsNOA',
    appId: '1:957380617692:ios:186fb139644c3ed79a1b19',
    messagingSenderId: '957380617692',
    projectId: 'notiva-61aff',
    storageBucket: 'notiva-61aff.firebasestorage.app',
    iosClientId: '957380617692-imk3edfaa2ccbi0iuoi0avg165d871jh.apps.googleusercontent.com',
    iosBundleId: 'com.example.notivaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHZL-m2A3mdfyvj97sysMz8571qGdmCmQ',
    appId: '1:957380617692:web:31e133cc606032aa9a1b19',
    messagingSenderId: '957380617692',
    projectId: 'notiva-61aff',
    authDomain: 'notiva-61aff.firebaseapp.com',
    storageBucket: 'notiva-61aff.firebasestorage.app',
    measurementId: 'G-4D7XW7PZJH',
  );
}
